dependencies:
  build:
   - maven:3.5.0
   - java:8.252.09
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt -y update
      - apt -y install python-pip
      - pip install requests
      - mvn package -DskipTests -Dmaven.javadoc.skip=true -B -V
ci:
  builds:
    - name: default
      build_target: default
