dependencies:
  build:
   - maven:3.6.3
   - java:11.0.8
   
build_targets:
  - name: default
    container:
      image: yourbase/yb_ubuntu:18.04
    environment:
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt -y update
      - apt -y install python-pip
      - pip install requests
      - mvn -B compile package
ci:
  builds:
    - name: default
      build_target: default
